-- ============================================================
-- LLM ANALYSIS + REQUIREMENT INTERACTIONS
-- ============================================================


-- ============================================================
-- 1. UPDATED_AT HELPER FUNCTION
-- ============================================================

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;


-- ============================================================
-- 2. LLM ANALYSIS
--
-- Stores the requirement-level analysis generated by the LLM.
--
-- A record can be associated with:
--   - a base resume
--   - a tailored resume
--   - or both
-- ============================================================

create table public.llm_analysis (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    job_id uuid not null
        references public.jobs(id)
        on delete cascade,

    resume_id uuid
        references public.resumes(id)
        on delete cascade,

    tailor_resume_id uuid
        references public.tailored_resumes(id)
        on delete cascade,

    requirements jsonb not null default '[]'::jsonb,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint llm_analysis_requirements_is_array
        check (
            jsonb_typeof(requirements) = 'array'
        ),

    constraint llm_analysis_resume_source_required
        check (
            resume_id is not null
            or tailor_resume_id is not null
        )
);


-- ============================================================
-- 3. LLM ANALYSIS INDEXES
-- ============================================================

create index idx_llm_analysis_user_id
    on public.llm_analysis(user_id);

create index idx_llm_analysis_job_id
    on public.llm_analysis(job_id);

create index idx_llm_analysis_resume_id
    on public.llm_analysis(resume_id)
    where resume_id is not null;

create index idx_llm_analysis_tailor_resume_id
    on public.llm_analysis(tailor_resume_id)
    where tailor_resume_id is not null;


-- ============================================================
-- 4. REQUIREMENT INTERACTIONS
--
-- Stores the user's answers/evidence when resolving
-- requirements before resume tailoring.
--
-- This is separate from the original LLM analysis.
-- ============================================================

create table public.requirement_interactions (
    id uuid primary key default gen_random_uuid(),

    llm_analysis_id uuid not null
        references public.llm_analysis(id)
        on delete cascade,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    requirement_id text not null,

    requirement text not null,

    has_experience boolean not null default false,

    user_evidence text,

    question text,

    hint text,

    answer text,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint requirement_interaction_unique
        unique (
            llm_analysis_id,
            requirement_id
        )
);


-- ============================================================
-- 5. REQUIREMENT INTERACTION INDEXES
-- ============================================================

create index idx_requirement_interactions_llm_analysis_id
    on public.requirement_interactions(llm_analysis_id);

create index idx_requirement_interactions_user_id
    on public.requirement_interactions(user_id);

create index idx_requirement_interactions_requirement_id
    on public.requirement_interactions(requirement_id);


-- ============================================================
-- 6. UPDATED_AT TRIGGERS
-- ============================================================

create trigger update_llm_analysis_updated_at
before update on public.llm_analysis
for each row
execute function public.update_updated_at_column();


create trigger update_requirement_interactions_updated_at
before update on public.requirement_interactions
for each row
execute function public.update_updated_at_column();


-- ============================================================
-- 7. ENABLE RLS
-- ============================================================

alter table public.llm_analysis
enable row level security;

alter table public.requirement_interactions
enable row level security;


-- ============================================================
-- 8. LLM ANALYSIS RLS POLICIES
-- ============================================================

create policy "Users can view their own LLM analysis"
on public.llm_analysis
for select
to authenticated
using (
    user_id = auth.uid()
);


create policy "Users can create their own LLM analysis"
on public.llm_analysis
for insert
to authenticated
with check (
    user_id = auth.uid()
);


create policy "Users can update their own LLM analysis"
on public.llm_analysis
for update
to authenticated
using (
    user_id = auth.uid()
)
with check (
    user_id = auth.uid()
);


create policy "Users can delete their own LLM analysis"
on public.llm_analysis
for delete
to authenticated
using (
    user_id = auth.uid()
);


-- ============================================================
-- 9. REQUIREMENT INTERACTION RLS POLICIES
-- ============================================================

create policy "Users can view their own requirement interactions"
on public.requirement_interactions
for select
to authenticated
using (
    user_id = auth.uid()
);


create policy "Users can create their own requirement interactions"
on public.requirement_interactions
for insert
to authenticated
with check (
    user_id = auth.uid()
);


create policy "Users can update their own requirement interactions"
on public.requirement_interactions
for update
to authenticated
using (
    user_id = auth.uid()
)
with check (
    user_id = auth.uid()
);


create policy "Users can delete their own requirement interactions"
on public.requirement_interactions
for delete
to authenticated
using (
    user_id = auth.uid()
);